# Auto-generated by setup.ps1 - do not edit manually.
# Runs the Cardinal Invoice ETL via the project `run.bat` launcher.

$ScriptDir  = $PSScriptRoot
$BatchFile  = Join-Path $ScriptDir "run.bat"
$MainScript = Join-Path $ScriptDir "Cardinal_Inv_Upload.py"
$ConfigFile = Join-Path $ScriptDir "config.yaml"
$EnvFile    = Join-Path $ScriptDir ".env"
$LogDir     = Join-Path $ScriptDir "log_python"
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir | Out-Null }
$LogFile    = Join-Path $LogDir "run_cardinal_etl.log"
$Timestamp  = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

Add-Content -Path $LogFile -Value ""
Add-Content -Path $LogFile -Value "[$Timestamp] ===== Task Started ====="
Add-Content -Path $LogFile -Value "[$Timestamp] Script dir : $ScriptDir"
Add-Content -Path $LogFile -Value "[$Timestamp] Run as     : $env:USERDOMAIN\$env:USERNAME"

# Pre-flight checks
$CheckFailed = $false

if (Test-Path $BatchFile) {
    Add-Content -Path $LogFile -Value "[$Timestamp] [OK]  run.bat                : $BatchFile"
} else {
    Add-Content -Path $LogFile -Value "[$Timestamp] [XX]  run.bat                : NOT FOUND at $BatchFile"
    $CheckFailed = $true
}

if (Test-Path $MainScript) {
    Add-Content -Path $LogFile -Value "[$Timestamp] [OK]  Cardinal_Inv_Upload.py : $MainScript"
} else {
    Add-Content -Path $LogFile -Value "[$Timestamp] [XX]  Cardinal_Inv_Upload.py : NOT FOUND at $MainScript"
    $CheckFailed = $true
}

if (Test-Path $ConfigFile) {
    Add-Content -Path $LogFile -Value "[$Timestamp] [OK]  config.yaml            : $ConfigFile"
} else {
    Add-Content -Path $LogFile -Value "[$Timestamp] [XX]  config.yaml            : NOT FOUND at $ConfigFile"
    $CheckFailed = $true
}

if (Test-Path $EnvFile) {
    Add-Content -Path $LogFile -Value "[$Timestamp] [OK]  .env                   : $EnvFile"
} else {
    Add-Content -Path $LogFile -Value "[$Timestamp] [XX]  .env                   : NOT FOUND at $EnvFile"
    $CheckFailed = $true
}

if ($CheckFailed) {
    Add-Content -Path $LogFile -Value "[$Timestamp] Pre-flight checks FAILED. Aborting."
    exit 1
}

Add-Content -Path $LogFile -Value "[$Timestamp] All pre-flight checks passed. Launching ETL..."

# Run ETL
& "$BatchFile"
$ExitCode = $LASTEXITCODE

$Timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
Add-Content -Path $LogFile -Value "[$Timestamp] ===== Task Finished - Exit Code: $ExitCode ====="

exit $ExitCode
